// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGDBmfaZceuSdtvTpw_uq4QdJUN4H_eYw',
    appId: '1:1053604861458:web:ad9594842358739dd42acb',
    messagingSenderId: '1053604861458',
    projectId: 'garcon-de615',
    authDomain: 'garcon-de615.firebaseapp.com',
    storageBucket: 'garcon-de615.firebasestorage.app',
    measurementId: 'G-Q78Y3YLSG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrUDfUQkvOImbCuoij0MaZKGlXGkyrpxs',
    appId: '1:1053604861458:android:e387c0f854fb705ad42acb',
    messagingSenderId: '1053604861458',
    projectId: 'garcon-de615',
    storageBucket: 'garcon-de615.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbbsPhhZG9AJeDqeJBRA8OcXVGeYren5Y',
    appId: '1:1053604861458:ios:4219cacadb3f6863d42acb',
    messagingSenderId: '1053604861458',
    projectId: 'garcon-de615',
    storageBucket: 'garcon-de615.firebasestorage.app',
    iosBundleId: 'com.example.garcon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbbsPhhZG9AJeDqeJBRA8OcXVGeYren5Y',
    appId: '1:1053604861458:ios:4219cacadb3f6863d42acb',
    messagingSenderId: '1053604861458',
    projectId: 'garcon-de615',
    storageBucket: 'garcon-de615.firebasestorage.app',
    iosBundleId: 'com.example.garcon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGDBmfaZceuSdtvTpw_uq4QdJUN4H_eYw',
    appId: '1:1053604861458:web:df0f60200306447dd42acb',
    messagingSenderId: '1053604861458',
    projectId: 'garcon-de615',
    authDomain: 'garcon-de615.firebaseapp.com',
    storageBucket: 'garcon-de615.firebasestorage.app',
    measurementId: 'G-YKCRZ3SW0L',
  );
}
